# Generated by Django 4.2.30 on 2026-07-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='inventory',
            field=models.SmallIntegerField(default=10),
        ),
    ]
